title: Curious Critters by Casai
baseurl: /
permalink: '/:title/'
palette: purple
header:
  has_nav: true
  logo_img: ''
  menu:
    actions:
      - label: Contact Us
        url: /content/contact
  title: Curious Critters by Casai
footer:
  content: '&copy; Curious Critters by Casai'
  has_nav: false
  has_social: true
  has_subscribe: false
  links:
    - new_window: true
      text: Made with Stackbit
      url: 'https://www.stackbit.com'
  logo_img: ''
  social_title: Follow Us on Social Media!
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
  - jekyll-font-awesome-sass
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
font-awesome:
  assets: true
